const SystemSetting = require('../models/SystemSetting');
const env = require('../config/env');

const DEFAULT_SETTINGS = [
  { settingKey: 'companyLogo', settingValue: '', settingType: 'file', description: 'Company logo file path/URL' },
  { settingKey: 'companyName', settingValue: env.COMPANY_NAME, settingType: 'text', description: 'Company name' },
  { settingKey: 'companyAddress', settingValue: env.COMPANY_ADDRESS, settingType: 'text', description: 'Company address' },
  { settingKey: 'phoneNumber', settingValue: env.COMPANY_PHONE, settingType: 'text', description: 'Company phone number' },
  { settingKey: 'email', settingValue: env.COMPANY_EMAIL, settingType: 'text', description: 'Company email' },
  { settingKey: 'website', settingValue: env.COMPANY_WEBSITE, settingType: 'text', description: 'Company website' },
  { settingKey: 'visitorIdPrefix', settingValue: env.VISITOR_ID_PREFIX, settingType: 'text', description: 'Visitor ID prefix' },
  { settingKey: 'visitorIdNumberingFormat', settingValue: 'PREFIX-YYYY-000000', settingType: 'text', description: 'Visitor ID numbering format' },
  { settingKey: 'autoCloseTime', settingValue: '00:00', settingType: 'text', description: 'Daily auto-close time (24h HH:mm)' },
  { settingKey: 'emailMandatory', settingValue: true, settingType: 'boolean', description: 'Whether Email ID is mandatory on the IN form' },
  {
    settingKey: 'visitorPolicyText',
    settingValue: 'I agree to company visitor policy.',
    settingType: 'text',
    description: 'Visitor policy checkbox text',
  },
  { settingKey: 'reportHeader', settingValue: env.COMPANY_NAME, settingType: 'text', description: 'Report header text' },
  { settingKey: 'reportFooter', settingValue: 'Generated by ISAZI Visitor Portal', settingType: 'text', description: 'Report footer text' },
  { settingKey: 'themeMode', settingValue: 'light', settingType: 'text', description: 'UI theme: light or dark' },
  { settingKey: 'qrUrl', settingValue: env.VISITOR_PORTAL_PUBLIC_URL, settingType: 'text', description: 'Public visitor portal QR URL' },
];

async function ensureDefaultSettings() {
  for (const setting of DEFAULT_SETTINGS) {
    await SystemSetting.findOneAndUpdate(
      { settingKey: setting.settingKey },
      { $setOnInsert: setting },
      { upsert: true, new: true }
    );
  }
}

async function getAllSettings() {
  const settings = await SystemSetting.find().sort({ settingKey: 1 });
  const map = {};
  settings.forEach((s) => {
    map[s.settingKey] = s.settingValue;
  });
  return map;
}

async function getSetting(key, fallback = null) {
  const setting = await SystemSetting.findOne({ settingKey: key });
  return setting ? setting.settingValue : fallback;
}

async function updateSettings(updates, adminUserId) {
  const keys = Object.keys(updates);
  await Promise.all(
    keys.map((key) =>
      SystemSetting.findOneAndUpdate(
        { settingKey: key },
        { settingValue: updates[key], updatedBy: adminUserId },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      )
    )
  );
  return getAllSettings();
}

module.exports = { ensureDefaultSettings, getAllSettings, getSetting, updateSettings, DEFAULT_SETTINGS };
